/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DeviceId = IDL.Text;
export const UserAnalytics = IDL.Record({
  'ip' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'imageCount' : IDL.Nat,
  'deviceType' : IDL.Text,
  'chatCount' : IDL.Nat,
  'lastSeen' : IDL.Int,
});
export const MessageId = IDL.Text;
export const Timestamp = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'text' : IDL.Text,
  'isUser' : IDL.Bool,
  'sender' : IDL.Text,
  'timestamp' : Timestamp,
});
export const DeviceSettings = IDL.Record({
  'userName' : IDL.Text,
  'fontSize' : IDL.Nat,
  'bgColor' : IDL.Text,
});
export const DeviceSettingsInput = IDL.Record({
  'userName' : IDL.Text,
  'fontSize' : IDL.Nat,
  'bgColor' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([DeviceId], [], []),
  'getAllUserAnalytics' : IDL.Func([], [IDL.Vec(UserAnalytics)], ['query']),
  'getHistory' : IDL.Func([DeviceId], [IDL.Vec(ChatMessage)], ['query']),
  'getSettings' : IDL.Func([DeviceId], [DeviceSettings], ['query']),
  'saveSettings' : IDL.Func([DeviceId, DeviceSettingsInput], [], []),
  'sendMessage' : IDL.Func([DeviceId, IDL.Text, IDL.Text], [IDL.Text], []),
  'trackUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : http_request_result,
        }),
      ],
      [http_request_result],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DeviceId = IDL.Text;
  const UserAnalytics = IDL.Record({
    'ip' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'imageCount' : IDL.Nat,
    'deviceType' : IDL.Text,
    'chatCount' : IDL.Nat,
    'lastSeen' : IDL.Int,
  });
  const MessageId = IDL.Text;
  const Timestamp = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'text' : IDL.Text,
    'isUser' : IDL.Bool,
    'sender' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const DeviceSettings = IDL.Record({
    'userName' : IDL.Text,
    'fontSize' : IDL.Nat,
    'bgColor' : IDL.Text,
  });
  const DeviceSettingsInput = IDL.Record({
    'userName' : IDL.Text,
    'fontSize' : IDL.Nat,
    'bgColor' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([DeviceId], [], []),
    'getAllUserAnalytics' : IDL.Func([], [IDL.Vec(UserAnalytics)], ['query']),
    'getHistory' : IDL.Func([DeviceId], [IDL.Vec(ChatMessage)], ['query']),
    'getSettings' : IDL.Func([DeviceId], [DeviceSettings], ['query']),
    'saveSettings' : IDL.Func([DeviceId, DeviceSettingsInput], [], []),
    'sendMessage' : IDL.Func([DeviceId, IDL.Text, IDL.Text], [IDL.Text], []),
    'trackUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : http_request_result,
          }),
        ],
        [http_request_result],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };